/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/*
 * Copyright (c) 2017, Joyent, Inc.
 */

/*
 * This module implements a "Moray" class that can be used to create
 * objects that act as an abstraction layer on top of the moray key/value store
 * used to store data about VMs.
 *
 * Instead of directly using a moray client and having to know the
 * implementation details about how VMAPI objects are stored, one can use
 * instances of the Moray class and use a simpler API that handles these
 * implementation details when reading and writing VMAPI objects to the moray
 * database.
 *
 * VMAPI uses one instance of Moray, and so most of the time it is used
 * as a singleton, even though any number instances of the Moray
 * class can be created.
 */

var assert = require('assert-plus');
var bunyan = require('bunyan');
var deepDiff = require('deep-diff');
var jsprim = require('jsprim');
var ldapjs = require('ldap-filter');
var once = require('once');
var restify = require('restify');
var sprintf = require('sprintf').sprintf;
var util = require('util');
var vasync = require('vasync');
var verror = require('verror');

var errors = require('../errors');
var common = require('../common');

var SELECT_ALL_FILTER = '(uuid=*)';
var PARAM_FILTER = '(%s=%s)';
var PARAM_FILTER_GE = '(%s>=%s)';
var PARAM_FILTER_LE = '(%s<=%s)';
var PARAM_FILTER_NE = '(!(%s=%s))';

// Fields that are deprecated that we're going to remove from VMs as we put
var DEPRECATED_VM_FIELDS = [
    'package_name',
    'package_version'
];


/*
 * The constructor for the Moray class.
 *
 * @param {Object} morayClient - the instance of a moray client that will be
 * used by this Moray instance to perform all operations on the moray database.
 *
 * @param {Object} options - an object with the following properties:
 *
 *  - {Object} log (optional): an instance of a bunyan logger that will be used
 *    to log messages.
 *
 *  - {Object} changefeedPublisher (required): an instance of
 *    changefeed.Publisher that will be used to publish changes to VM objects
 *    performed via this Moray abstraction layer.
 */
function Moray(morayClient, options) {
    assert.object(morayClient, 'morayClient');
    assert.object(options, 'options');
    assert.optionalObject(options.log, 'options.log');
    assert.object(options.changefeedPublisher, 'options.changefeedPublisher');

    this._morayClient = morayClient;

    this.log = options.log || bunyan.createLogger({
        name: 'moray',
        level: options.logLevel || 'info',
        serializers: restify.bunyan.serializers
    });

    this.changefeedPublisher = options.changefeedPublisher;

    this._bucketsSetup = false;
    this._settingUpBuckets = false;
    this._lastBucketsSetupError = null;

    this._reindexingBuckets = false;
}


/*
 * Returns true if the "err" error object represents a transient error (an error
 * that could be solved after retrying the same action) that can happen during
 * the process of setting up Moray buckets.
 */
Moray.prototype.isBucketsSetupErrorTransient =
    function isBucketsSetupErrorTransient(err) {
        assert.object(err, 'err');
        assert.string(err.name, 'err.name');

        var nonTransientErrName;
        var NON_TRANSIENT_ERROR_NAMES = [
            /* Errors sent by the moray server */
            'InvalidBucketConfigError',
            'InvalidBucketNameError',
            'InvalidIndexDefinitionError',
            'NotFunctionError',
            'BucketVersionError',
            /* Custom errors generated by this Moray abstraction layer */
            'InvalidIndexesRemovalError'
        ];

        for (var idx in NON_TRANSIENT_ERROR_NAMES) {
            nonTransientErrName = NON_TRANSIENT_ERROR_NAMES[idx];
            if (verror.hasCauseWithName(err, nonTransientErrName)) {
                return false;
            }
        }

        return true;
    };


/*
 * Sets up VMAPI's moray buckets, including creating them if they're
 * missing, or updating them if they already exist. Calls the 'callback'
 * function when that setup completed.
 *
 * It does not perform any reindexing of rows that would need to be reindexed
 * after a bucket was updated to add one or more indexes. To reindex rows of all
 * buckets, use the "Moray.prototype.reindexBuckets" function.
 *
 * If the setup results in an error, the first argument of the 'callback'
 * function is an Error object. The
 * 'Moray.prototype.isBucketsSetupErrorNonTransient' function can be used to
 * determine whether that error is non transient, and how to act on it depending
 * on the program's expectations and behavior.
 *
 * The "Moray.prototype.setupBuckets" function can be called more than once per
 * instance of the Moray constructor, as long as each call is made after the
 * previous setup process terminated, either successfully or with an error, by
 * calling the 'callback' function passed as a parameter. Calling this method
 * while a previous call is still in flight will throw an error.
 */
Moray.prototype.setupBuckets =
    function setupBuckets(bucketsConfig, callback) {
        assert.object(bucketsConfig, 'bucketsConfig');
        assert.object(bucketsConfig.VMS, 'bucketsConfig.VMS');
        assert.object(bucketsConfig.SERVER_VMS, 'bucketsConfig.SERVER_VMS');
        assert.object(bucketsConfig.VM_ROLE_TAGS, 'bucketsConfig.VM_ROLE_TAGS');

        var self = this;
        var bucketsList = [];
        var bucketConfig;

        if (self._settingUpBuckets === true) {
            throw new Error('setupBuckets cannot be called when a setup ' +
                'process is in progress');
        }

        self._lastBucketsSetupError = null;
        self._settingUpBuckets = true;

        self.log.info({bucketsConfig: bucketsConfig},
            'Setting up moray buckets...');

        self._VMS_BUCKET_NAME = bucketsConfig.VMS.name;
        self._VM_ROLE_TAGS_BUCKET_NAME = bucketsConfig.VM_ROLE_TAGS.name;

        for (bucketConfig in bucketsConfig) {
            bucketsList.push(bucketsConfig[bucketConfig]);
        }

        self._trySetupBuckets(bucketsList, function (setupBucketsErr) {
            self._settingUpBuckets = false;
            self._lastBucketsSetupError = setupBucketsErr;

            if (setupBucketsErr) {
                self.log.error({ error: setupBucketsErr },
                    'Error when setting up moray buckets');
            } else {
                self.log.info('Buckets have been setup successfully');
                self._bucketsSetup = true;
            }

            callback(setupBucketsErr);
        });
    };


/*
 * Returns true if VMAPI's moray buckets have been setup successfully, false
 * otherwise.
 */
Moray.prototype.bucketsSetup = function bucketsSetup() {
    return this._bucketsSetup;
};


/*
 * Returns an Error instance that represents the latest error that occured
 * during the process of setting up Moray buckets (but not reindexing), or null
 * if no error occurred since the last time "Moray.prototype.setupBuckets" was
 * called.
 */
Moray.prototype.lastBucketsSetupError = function lastBucketsSetupError() {
    return this._lastBucketsSetupError;
};


/*
 * Returns a string representing an error message to signal that the
 * Moray layer's setup process has not completed yet.
 */
Moray.prototype._createMorayBucketsNotSetupErrMsg =
    function _createMorayBucketsNotSetupErrMsg() {
        var errMsg = 'moray buckets are not setup';

        if (this._lastBucketsSetupError !== null) {
            errMsg += ', reason: ' + this._lastBucketsSetupError;
        }

        return errMsg;
    };


/*
 * Pings Moray by calling its ping method
 */
Moray.prototype.ping = function (callback) {
    // Default ping timeout is 1 second
    return this._morayClient.ping({ log: this.log }, callback);
};


/*
 * Gets a VM object from moray. uuid is required param and owner_uuid is
 * optional
 */
Moray.prototype.getVm = function getVm(params, cb) {
    var uuid = params.uuid;
    var owner = params.owner_uuid;
    var filter = '';
    var error;

    if (!this.bucketsSetup()) {
        cb(new verror.VError('Moray buckets are not setup',
            this._lastBucketsSetupError));
        return;
    }

    if (!common.validUUID(uuid)) {
        error = [ errors.invalidUuidErr('uuid') ];
        return cb(new errors.ValidationFailedError('Invalid Parameters',
            error));
    }

    filter += sprintf(PARAM_FILTER, 'uuid', uuid);

    if (owner) {
        if (!common.validUUID(owner)) {
            error = [ errors.invalidUuidErr('owner_uuid') ];
            return cb(new errors.ValidationFailedError('Invalid Parameters',
                error));
        }

        filter += sprintf(PARAM_FILTER, 'owner_uuid', owner);
        filter = '(&' + filter + ')';
    }


    var vm;
    var req = this._morayClient.findObjects(this._VMS_BUCKET_NAME, filter);

    req.once('error', function (err) {
        return cb(err);
    });

    // For getVm we want the first result (and there should only be one result)
    req.once('record', function (object) {
        vm = object.value;
    });

    return req.once('end', function () {
        return cb(null, vm);
    });
};


/*
 * Gets VMs from a list of UUIDs
 */
Moray.prototype.getVms = function (uuids, cb) {
    var filter = '';
    var i;

    if (!this.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    for (i = 0; i < uuids.length; i++) {
        filter += sprintf(PARAM_FILTER, 'uuid', uuids[i]);
    }

    filter = '(|' + filter + ')';
    var vms = [];
    var req = this._morayClient.findObjects(this._VMS_BUCKET_NAME, filter);

    req.once('error', function (err) {
        return cb(err);
    });

    req.on('record', function (object) {
        vms.push(common.translateVm(object.value, true));
    });

    req.once('end', function () {
        return cb(null, vms);
    });
};


/*
 * It takes same arguments than listVms/countVms do, and will return
 * cb(error, filter), where filter is the search filter based on params.
 */
Moray.prototype._vmsListParams = function (params, cb) {
    var filter = [];
    var error;

    if (params.uuid) {
        if (!common.validUUID(params.uuid)) {
            error = [ errors.invalidUuidErr('uuid') ];
            return cb(new errors.ValidationFailedError('Invalid Parameters',
                error));
        }
        filter.push(sprintf(PARAM_FILTER, 'uuid', params.uuid));
    } else if (params.uuids) {
        var uuidsFilter = '';

        params.uuids.forEach(function (uuid) {
            uuidsFilter += sprintf(PARAM_FILTER, 'uuid', uuid);
        });

        uuidsFilter = '(|' + uuidsFilter + ')';
        filter.push(uuidsFilter);
    }

    if (params.owner_uuid) {
        if (!common.validUUID(params.owner_uuid)) {
            error = [ errors.invalidUuidErr('owner_uuid') ];
            return cb(new errors.ValidationFailedError('Invalid Parameters',
                error));
        }
        filter.push(sprintf(PARAM_FILTER, 'owner_uuid', params.owner_uuid));
    }

    if (params.image_uuid) {
        filter.push(sprintf(PARAM_FILTER, 'image_uuid', params.image_uuid));
    }

    if (params.server_uuid) {
        filter.push(sprintf(PARAM_FILTER, 'server_uuid', params.server_uuid));
    }

    if (params.billing_id) {
        filter.push(sprintf(PARAM_FILTER, 'billing_id', params.billing_id));
    }

    if (params.package_name) {
        filter.push(sprintf(PARAM_FILTER, 'package_name', params.package_name));
    }

    if (params.package_version) {
        filter.push(sprintf(
                    PARAM_FILTER, 'package_version', params.package_version));
    }

    if (params.brand) {
        filter.push(sprintf(PARAM_FILTER, 'brand', params.brand));
    }

    if (typeof (params.docker) === 'boolean') {
        var filterStr = params.docker ? PARAM_FILTER : PARAM_FILTER_NE;
        filter.push(sprintf(filterStr, 'docker', true));
    }

    if (params.alias) {
        var str;
        // When doing an update we don't want to use a wildcard match
        if (params._update) {
            str = sprintf(PARAM_FILTER, 'alias', params.alias);
        } else {
            str = sprintf(PARAM_FILTER, 'alias', params.alias + '*');
        }
        filter.push(str);
    }

    if (params.ram || params.max_physical_memory) {
        var value = params.ram || params.max_physical_memory;
        filter.push(sprintf(PARAM_FILTER, 'max_physical_memory', value));
    }

    if (params.state) {
        if (params.state === 'active') {
            filter.push('(&(!(state=destroyed))(!(state=failed)))');
        } else {
            filter.push(sprintf(PARAM_FILTER, 'state', params.state));
        }
    }

    if (params.create_timestamp !== undefined) {
        assert.number(params.create_timestamp,
            'If not undefined, params.create_timestamp must be a number');
        filter.push(sprintf(PARAM_FILTER, 'create_timestamp',
            params.create_timestamp));
    }

    this._addTagsFilter(params, filter);

    return cb(null, filter);
};


/*
 * This is a bit different to getVm.
 * For this one we need exactly the VM that has the provided UUID
 */
Moray.prototype._getVmObject = function (uuid, cb) {
    if (!this.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    this._morayClient.getObject(this._VMS_BUCKET_NAME, uuid,
        function onGetObject(err, obj) {
            if (err) {
                cb(err);
            } else {
                cb(null, obj.value);
            }
        });
};


/*
 * Raw LDAP search filter
 */
Moray.prototype._parseLdapFilter = function (query, cb) {
    var error;

    if (!query) {
        return cb(null, []);
    }

    if (typeof (query) !== 'string') {
        error = [ errors.invalidParamErr('query', 'Query must be a string') ];
        return cb(new errors.ValidationFailedError('Invalid Parameters',
            error));
    }

    // TODO additional parsing and validation?
    if (query === '') {
        error = [ errors.invalidParamErr('query', 'Empty query') ];
        return cb(new errors.ValidationFailedError('Invalid Parameters',
            error));
    }

    query = query.replace(/\(ram/g, '(max_physical_memory');

    return cb(null, [query]);
};


/*
 * Parse a predicate query that allows us to create an ldap filter from an
 * easier syntax/format
 */
Moray.prototype._parsePredicate = function (jsonPredicate, cb) {
    if (!jsonPredicate) {
        return cb(null, []);
    }

    var predicate = JSON.parse(jsonPredicate);
    var query;
    try {
        query = common.toLdapQuery(predicate);
    } catch (error) {
        return cb(error);
    }

    return cb(null, [query]);
};


/*
 * Take all different ways to query listVms/countVms, and create a single
 * LDAP filter to search Moray with.
 */
Moray.prototype._createSearch = function (params, cb) {
    var self = this;

    self._parseLdapFilter(params.query, function (err, ldapSearch) {
        if (err) {
            return cb(err);
        }

        self._parsePredicate(params.predicate, function (err2, predSearch) {
            if (err2) {
                return cb(err2);
            }

            self._vmsListParams(params, function (err3, paraSearch) {
                if (err3) {
                    return cb(err3);
                }

                var filter = [].concat(ldapSearch, predSearch, paraSearch);

                var query;
                if (filter.length === 0) {
                    query = SELECT_ALL_FILTER;
                } else if (filter.length === 1) {
                    query = filter[0];
                } else {
                    query = '(&' + filter.join('') + ')';
                }

                return cb(null, query);
            });
        });
    });
};


/**
 * List all VMs for a given server from the VM bucket.
 * @param  {string}     uuid uuid of the server whos vms should be fetched.
 * @param  {Function}   cb  function of the form function(err, vms) {...}
 */
Moray.prototype.listVmsForServer = function listVmsForServer(uuid, cb) {
    var self = this;
    var vms = {};
    var vm;
    var filter = sprintf(PARAM_FILTER, 'server_uuid', uuid);

    if (!self.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    filter += sprintf(PARAM_FILTER_NE, 'state', 'destroyed');
    filter = '(&' + filter + ')';

    var req = self._morayClient.findObjects(self._VMS_BUCKET_NAME, filter);

    req.once('error', function (error) {
        return cb(error);
    });

    req.on('record', function (object) {
        if (object && object.value) {
            vm = common.translateVm(object.value, false);
            vms[vm.uuid] = vm;
        }
    });

    return req.once('end', function () {
        return cb(null, vms);
    });
};


/*
 * List VMs
 */
Moray.prototype.listVms = function listVms(params, raw, cb) {
    var self = this;

    // Allow calling listVms with no post-processing of the VM object
    if (typeof (raw) === 'function') {
        cb = raw;
        raw = false;
    }

    if (!self.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    self._createSearch(params, function (err, ldapFilter) {
        if (err) {
            return cb(err);
        }

        self.log.info({ filter: ldapFilter }, 'listVms filter');

        var vm;
        var vms = [];
        var filterOptions = _addPaginationOptions(params, ldapFilter);
        var req = self._morayClient.findObjects(self._VMS_BUCKET_NAME,
            filterOptions.ldapFilter, filterOptions.morayOptions);

        req.once('error', function (error) {
            return cb(error);
        });

        req.on('record', function (object) {
            if (object && object.value) {
                vm  = (raw ? object.value
                           : common.translateVm(object.value, true));
                // The way the API works wrt markers is that the client
                // requests the first page of results. Then to get the second
                // page of results, the client adds a marker to the query
                // string. This marker identifies the last entry of the first
                // page. Thus, if a marker is used, do not include the VM that
                // corresponds to that marker in the results of a given page,
                // as the client already got it with the previous page.
                if (!params.marker ||
                    !common.markerIdentifiesObject(params.marker, vm)) {
                    vms.push(vm);
                }
            }
        });

        return req.once('end', function () {
            return cb(null, vms);
        });
    });
};


/*
 * Given the same filter listVms uses, this function transforms it into
 * something which can be send to moray through RAW sql method.
 *
 * This method will return the number of total machines matching the given
 * params conditions using the traditional cb(err, counter) approach.
 */
Moray.prototype.countVms = function countVms(params, cb) {
    var self = this;

    if (!self.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    self._createSearch(params, function (err, string) {
        if (err) {
            return cb(err);
        }

        var options = {
            limit: 1
        };

        self.log.info({ filter: string }, 'countVms filter');
        var req = self._morayClient.findObjects(self._VMS_BUCKET_NAME, string,
            options);
        var count = 0;

        req.on('record', function (r) {
            if (r && r['_count']) {
                count = Number(r['_count']);
            }
        });

        req.once('error', function (error) {
            return cb(error);
        });

        return req.once('end', function () {
            return cb(null, count);
        });
    });
};


/*
 * Takes two objects, "oldObject" and "newObject" and computes the differences
 * between them. Returns an array that contains the properties that are not
 * equal in oldObject and newObject. If there's no difference between oldObject
 * and newObject, it returns an empty array.
 *
 * @param {Object} oldObject
 * @param {Object} newObject
 * @param {Object} log - the log instance used to log messages.
 */
function computeDiff(oldObject, newObject, log) {
    assert.object(oldObject, 'oldObject');
    assert.object(newObject, 'newObject');
    assert.object(log, 'log');

    var diffs = [];
    var diffResults = deepDiff.diff(oldObject, newObject);
    if (diffResults && diffResults.length) {
        for (var i = 0; i < diffResults.length; i++) {
            var path = diffResults[i].path;
            if (path && path[0]) {
                diffs.push(path[0]);
            } else {
                log.warn('diffResult path not properly set: %j',
                    diffResults[i]);
            }
        }
    }

    return diffs;
}


/*
 * Puts a VM. If it doesn't exist it gets created, if it does exist it gets
 * updated. We no longer need to execute partial updates
 */
Moray.prototype.putVm = function putVm(uuid, vm, oldVm, cb) {
    var self = this;

    assert.uuid(uuid, 'uuid');
    assert.object(vm, 'vm');
    assert.object(oldVm, 'oldVm');
    assert.func(cb, 'cb');

    assert.object(self.changefeedPublisher, 'self.changefeedPublisher');

    var VM_CHANGEFEED_RESOURCE_NAME = 'vm';
    var vmObject = self._toMorayVm(vm);

    if (!this.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    /*
     * Normalize both objects to not contain properties for values that are not
     * set (null, undefined or empty string). This way, we can make sure that
     * the computation of the differences between "oldVm" and "vm" won't find
     * differences between non-existing properties and existing properties with
     * values that are unset.
     */
    oldVm = common.translateVm(oldVm, false);
    vm = common.translateVm(vm, false);

    self.log.debug({oldVm: oldVm, vm: vm}, 'putting VM');

    self._morayClient.putObject(self._VMS_BUCKET_NAME, uuid, vmObject,
        function onPutObj(putObjErr) {
            var diffs;

            if (!putObjErr) {
                self.log.debug('VM successfully put to moray');

                if (oldVm && self.changefeedPublisher) {
                    diffs = computeDiff(oldVm, vm, self.log);
                    self.log.debug({diffs: diffs},
                        'publishing change to changefeed');
                    common.publishChange(self.changefeedPublisher,
                        VM_CHANGEFEED_RESOURCE_NAME, diffs, vm.uuid,
                        function onChangePublished(publishErr) {
                            if (publishErr) {
                                self.log.error({
                                    err: publishErr
                                }, 'error when publishing change to ' +
                                    'changefeed');
                            } else {
                                self.log.debug('change published to ' +
                                    'changefeed successfully');
                            }

                            cb(publishErr);
                        });
                } else {
                    self.log.debug('not publishing change to changefeed');
                    cb(putObjErr);
                }
            } else {
                self.log.error({err: putObjErr},
                    'error when putting VM to moray');
                cb(putObjErr);
            }
        });
};


/*
 * Deletes *all* VMs that match the filter generated from "params".
 * This API is INTERNAL and should ONLY BE USED FOR WRITING TESTS.
 */
Moray.prototype.delVms = function delVms(params, cb) {
    assert.object(params, 'params');
    assert.func(cb, 'cb');
    var self = this;

    if (!self.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    self._createSearch(params, function (err, filter) {
        if (err) {
            return cb(err);
        }

        // Make sure that the filter is not the filter that selects all VMs.
        // We don't want to allow deletion of all VMs via this API.
        assert.notEqual(filter, SELECT_ALL_FILTER);
        return self._morayClient.deleteMany(self._VMS_BUCKET_NAME, filter,
            params, cb);
    });
};


/*
 * Marks a VM as destroyed
 */
Moray.prototype.markAsDestroyed = function markAsDestroyed(vm, callback) {
    assert.object(vm, 'vm');
    assert.func(callback, 'callback');

    var self = this;

    var oldVm = jsprim.deepCopy(vm);

    if (!self.bucketsSetup()) {
        callback(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    var state = (vm.state === 'provisioning') ? 'failed' : 'destroyed';

    vm.state = state;
    vm.zone_state = state;
    if (state === 'destroyed') {
        vm.destroyed = new Date();
    }

    self.putVm(vm.uuid, vm, oldVm, function (err) {
        if (err) {
            callback(err);
        } else {
            callback(null, vm);
        }
    });
};


/*
 * Returns a list of objects each representing a sort option to pass
 * to moray according to the sort parameter "sortparam" that was passed
 * by the HTTP client.
 * If no sort option needs to be set, an empty array is returned.
 */
function _sortOptionsFromSortParam(sortParam) {
    assert.optionalString(sortParam, 'sortParam must be a string or undefined');

    var sortOptions = [];
    var order;

    if (sortParam) {
        var splitted = sortParam.split('.');
        var property = splitted[0];

        if (property == 'ram') {
            property = 'max_physical_memory';
        }

        if (splitted.length == 2) {
            order = splitted[1] || common.DEFAULT_SORT_ORDER;
        }

        sortOptions.push({
            attribute: property,
            order: order
        });
    }

    // If the sorting options will not output a totally ordered results set,
    // add a sort option that will. This makes the last item of any
    // results set (even when not using a marker, for example when getting
    // the first page of paginated results) usable as a marker for getting
    // the next page of paginated results.
    var sortOptionsHasStrictTotalOrder =
        sortOptions.some(function (sortOption) {
            return common.isStrictTotalOrderField(sortOption.attribute);
        });

    if (!sortOptionsHasStrictTotalOrder) {
        sortOptions.push({
            attribute: common.strictTotalOrderField(),
            order: common.DEFAULT_SORT_ORDER
        });
    }

    return sortOptions;
}


/*
 * Build the appropriate LDAP filters for the marker "marker" and the sort
 * options "sortOptions". Returns a list of strings representing ldap
 * filters. An empty list is returned if a filter is not required for the
 * corresponding marker and sortOptions.
 */
function _buildFiltersFromMarker(marker, sortOptions) {
    assert.object(marker, 'marker must be an object');
    assert.arrayOfObject(sortOptions,
        'sortOptions must be an array of objects');

    var markerFilters = [];

    var sortOptionsLookup = {};
    sortOptions.forEach(function (sortOption) {
        assert.string(sortOption.attribute,
            'sortOption.attribute must be a string');
        assert.string(sortOption.order,
            'sortOption.order must be a string');

        sortOptionsLookup[sortOption.attribute] = sortOption.order;
    });

    Object.keys(marker).forEach(function (markerKey) {
        var markerValue = '' + marker[markerKey];
        var order;
        var ldapFilter;

        if (markerValue !== null) {
            order = sortOptionsLookup[markerKey];
            if (order === undefined)
                order = common.DEFAULT_SORT_ORDER;

            if (common.isSortOrderDescending(order)) {
                ldapFilter = new ldapjs.LessThanEqualsFilter({
                    attribute: markerKey,
                    value: markerValue
                });
            } else {
                ldapFilter = new ldapjs.GreaterThanEqualsFilter({
                    attribute: markerKey,
                    value: markerValue
                });
            }

            markerFilters.push(ldapFilter);
        }
    });

    return markerFilters;
}


/*
 * Augments moray params and ldapFilter used to query moray with
 * relevant moray options and ldap filter according to pagination options.
 *
 * Returns an object with two sub-objects:
 * - morayOptions: an object that contains sort, limit and offset options for
 * moray.
 * - ldapFilter: a string that contains the ldapFilter corresponding to the
 * original ldap filter + the additional filters to handle pagination when
 * using the "marker" querystring parameter.
 */
function _addPaginationOptions(params, ldapFilterString) {
    assert.object(params, 'params must be an object');
    assert.string(ldapFilterString, 'ldapFilter must be a string');

    var sortOptions = _sortOptionsFromSortParam(params.sort);

    var markerFilters, ldapFilterObject, combinedFilters;

    var morayOptions = {
        limit: params.limit,
        offset: params.offset
    };

    var paginationOptionsOut = {
        ldapFilter: ldapFilterString,
        morayOptions: morayOptions
    };

    morayOptions.sort = sortOptions;

    // If a marker is used, the entry corresponding to that marker must not
    // be returned in the result, but will be included in the filter, so
    // increment the limit to get the correct number of entries once the
    // entry that corresponds to the marker is removed
    if (morayOptions.limit !== undefined && params.marker) {
        morayOptions.limit += 1;
    }

    if (params.marker) {
        markerFilters = _buildFiltersFromMarker(params.marker, sortOptions);
        ldapFilterObject = ldapjs.parse(ldapFilterString);
        assert.object(ldapFilterObject, 'ldapFilterObject must be an object');

        combinedFilters = [ldapFilterObject].concat(markerFilters);
        paginationOptionsOut.ldapFilter = new ldapjs.AndFilter({
            filters: combinedFilters
        }).toString();
    }

    return paginationOptionsOut;
}


/*
 * Parses tag.xxx=yyy from the request params
 *   a="tag.role"
 *   m=a.match(/tag\.(.*)/)
 *   [ 'tag.role',
 *     'role',
 *     index: 0,
 *     input: 'tag.role' ]
 */
Moray.prototype._addTagsFilter = function (params, filter) {
    Object.keys(params).forEach(function (key) {
        var matches = key.match(/tag\.(.*)/);
        if (matches) {
            var tagKey = matches[1].replace(/-/g, '%2D');
            var tagString;
            var value = params[key];

            // Numbers have to be backwards compatible if VMs with numbers as
            // key values already exist
            if (value === 'true' || value === 'false') {
                var bool = '*-' + tagKey + '=' + '%b{' + value + '}' + '-*';
                tagString = '*-' + tagKey + '=' + value + '-*';
                filter.push(sprintf('(|(tags=%s)(tags=%s))', bool, tagString));

            } else if (!isNaN(Number(value))) {
                var num = '*-' + tagKey + '=' + '%n{' + value + '}' + '-*';
                tagString = '*-' + tagKey + '=' + value + '-*';
                filter.push(sprintf('(|(tags=%s)(tags=%s))', num, tagString));

            } else {
                value = value.replace(/-/g, '%2D');
                tagString = '*-' + tagKey + '=' + value + '-*';
                filter.push(sprintf(PARAM_FILTER, 'tags', tagString));
            }
        }
    });
};


/*
 * Tries to setup VMAPI's moray buckets as specified by the array "buckets".
 * Calls the function "cb" when done. If there was an error, the "cb" function
 * is called with an error object as its first parameter, otherwise it is called
 * without passing any parameter.
 */
Moray.prototype._trySetupBuckets =
    function _trySetupBuckets(buckets, cb) {
        assert.arrayOfObject(buckets, 'buckets');
        assert.func(cb, 'cb');

        var self = this;

        vasync.forEachPipeline({
            func: function setupEachBucket(newBucketConfig, done) {
                var bucketName = newBucketConfig.name;
                assert.string(bucketName, 'bucketName');

                self._trySetupBucket(bucketName, newBucketConfig, done);
            },
            inputs: buckets
        }, cb);
    };


/*
 * Returns true if the updating a moray bucket from the bucket schema
 * "oldBucketSchema" to "newBucketSchema" would imply removing at least one
 * index. Returns false otherwise.
 */
function indexesRemovedBySchemaChange(oldBucketSchema, newBucketSchema) {
    assert.object(oldBucketSchema, 'oldBucketSchema');
    assert.object(newBucketSchema, 'newBucketSchema');

    var oldBucketIndexNames = [];
    var newBucketIndexNames = [];

    if (oldBucketSchema.index) {
        oldBucketIndexNames = Object.keys(oldBucketSchema.index);
    }

    if (newBucketSchema.index) {
        newBucketIndexNames = Object.keys(newBucketSchema.index);
    }

    var indexesRemoved =
        oldBucketIndexNames.filter(function indexMissingInNewSchema(indexName) {
            return newBucketIndexNames.indexOf(indexName) === -1;
        });

    return indexesRemoved;
}


/*
 * Tries to set up bucket with name "bucketName" to have configuration
 * "bucketConfig". The setup process includes, in the following order:
 *
 * 1. creating the bucket if it does not exist.
 *
 * 2. updating the bucket's indexes to add indexes. Indexes cannot be removed
 * because it's a backward incompitble change: if a code rollback is performed,
 * older code that would rely on the deleted indexes wouldn't be able to work
 * properly, and removing indexes will generate an error.
 *
 */
function _trySetupBucket(bucketName, bucketConfig, cb) {
    assert.string(bucketName, 'bucketName');
    assert.object(bucketConfig, 'bucketConfig');
    assert.object(bucketConfig.schema, 'bucketConfig.schema');
    assert.optionalObject(bucketConfig.schema.options,
        'bucketConfig.schema.options');
    if (bucketConfig.schema.options) {
        assert.optionalNumber(bucketConfig.schema.options.version,
            'bucketConfig.schema.options.version');
    }

    assert.func(cb, 'cb');

    var self = this;

    var newBucketSchema = bucketConfig.schema;

    vasync.waterfall([
        function loadBucket(next) {
            self._getBucket(bucketName, function (err, oldBucketSchema) {
                if (err &&
                    verror.hasCauseWithName(err, 'BucketNotFoundError')) {
                    err = null;
                }

                next(err, oldBucketSchema);
            });
        },
        function createBucket(oldBucketSchema, next) {
            if (!oldBucketSchema) {
                self.log.info({bucketName: bucketName},
                    'Bucket not found, creating it...');
                self._createBucket(bucketName, bucketConfig.schema,
                    function createDone(createErr) {
                        if (createErr) {
                            self.log.error({
                                bucketName: bucketName,
                                error: createErr.toString()
                            }, 'Error when creating bucket');
                        } else {
                            self.log.info('Bucket ' +
                                bucketName +
                                    ' created successfully');
                        }

                        next(createErr, oldBucketSchema);
                    });
             } else {
                self.log.info({bucketName: bucketName},
                    'Bucket already exists, not creating it.');
                next(null, oldBucketSchema);
            }
        },
        function updateBucketSchema(oldBucketSchema, next) {
            assert.optionalObject(oldBucketSchema, 'oldBucketSchema');

            var oldVersion = 0;
            var newVersion = 0;
            var removedIndexes = [];

            if (oldBucketSchema && oldBucketSchema.options &&
                oldBucketSchema.options.version) {
                oldVersion = oldBucketSchema.options.version;
            }

            if (newBucketSchema.options && newBucketSchema.options.version) {
                newVersion = newBucketSchema.options.version;
            }

            /*
             * If the bucket's version was bumped, update the bucket, otherwise:
             *
             * 1. the version number wasn't bumped because no change was made
             * and there's nothing to do.
             *
             * 2. the version number is lower than the current version number in
             * moray. This can be the result of a code rollback. Since we make
             * only backward compatible changes for moray buckets, and
             * decrementing a bucket's version number is an error, it's ok to
             * not change the bucket.
             */
            if (oldBucketSchema && newVersion > oldVersion) {
                removedIndexes = indexesRemovedBySchemaChange(oldBucketSchema,
                    newBucketSchema);
                if (removedIndexes.length > 0) {
                    /*
                     * Removing indexes is considered to be a backward
                     * incompatible change. We don't allow them so that after
                     * rolling back to a previous version of the code, the code
                     * can still use any index that it relies on.
                     */
                    next(new errors.InvalidIndexesRemovalError(removedIndexes));
                    return;
                }

                self.log.info('Updating bucket ' + bucketName + ' from ' +
                    'version ' + oldVersion + ' to version ' + newVersion +
                    '...');

                self._updateBucket(bucketName, newBucketSchema,
                    function updateDone(updateErr) {
                        if (updateErr) {
                            self.log.error({error: updateErr},
                                'Error when updating bucket ' +
                                    bucketName);
                        } else {
                            self.log.info('Bucket ' + bucketName +
                                ' updated successfully');
                        }

                        next(updateErr);
                    });
            } else {
                self.log.info('Bucket ' + bucketName + ' already at version ' +
                    '>= ' + newVersion + ', no need to update it');
                next(null);
            }
        }
    ], cb);
}
Moray.prototype._trySetupBucket = _trySetupBucket;


/*
 * Gets a bucket
 */
Moray.prototype._getBucket = function (name, cb) {
    this._morayClient.getBucket(name, cb);
};


/*
 * Creates a bucket
 */
Moray.prototype._createBucket = function (name, config, cb) {
    this._morayClient.createBucket(name, config, cb);
};


/*
 * Deletes a bucket
 */
Moray.prototype._deleteBucket = function (name, cb) {
    this._morayClient.delBucket(name, cb);
};


Moray.prototype._updateBucket = function (name, schema, cb) {
    this._morayClient.updateBucket(name, schema, cb);
};


/*
 * Converts to a valid moray VM object
 */
Moray.prototype._toMorayVm = function (vm) {
    var copy = common.clone(vm);
    var idx;

    var timestamps = ['create_timestamp', 'last_modified', 'destroyed' ];
    timestamps.forEach(function (key) {
        var isDate = (copy[key] !== null && typeof (copy[key]) === 'object' &&
            copy[key].getMonth !== undefined);

        if (typeof (copy[key]) === 'string') {
            copy[key] = new Date(copy[key]).getTime();
        } else if (isDate) {
            copy[key] = copy[key].getTime();
        }
    });

    // Remove deprecated fields
    for (idx = 0; idx < DEPRECATED_VM_FIELDS.length; idx++) {
        delete copy[DEPRECATED_VM_FIELDS[idx]];
    }

    // Only stringify if they are object
    var fields = ['nics', 'datasets', 'snapshots', 'internal_metadata',
        'customer_metadata'];
    fields.forEach(function (key) {
        if (copy[key] && typeof (copy[key]) === 'object') {
            copy[key] = JSON.stringify(copy[key]);
        }
    });

    if (copy.disks && typeof (copy.disks) === 'object') {
        // We don't really use it at the top level for KVM, but doing this in
        // moray (and hiding it) allows us to index the image_uuid column and
        // be able to search KVM VMs by image_uuid
        if (copy.disks[0] && copy.disks[0].image_uuid !== undefined) {
            copy.image_uuid = copy.disks[0].image_uuid;
        }
        copy.disks = JSON.stringify(copy.disks);
    }

    if (copy.tags && typeof (copy.tags) === 'object') {
        if ((Object.keys(copy.tags).length > 0)) {
            var tags = common.objectToTagFormat(copy.tags);
            copy.tags = tags;
        // Don't want to store '{}'
        } else {
            delete copy.tags;
        }
    }

    return copy;
};



/**
 * VM Role Tags
 */


/*
 * Get all VM role_tags that match one or more role_tags. Returns a list of
 * VM UUIDs.
 */
Moray.prototype.getRoleTags = function (roleTags, cb) {
    var filter = '';

    if (!this.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    roleTags.forEach(function (roleTag) {
        filter += sprintf(PARAM_FILTER, 'role_tags', roleTag);
    });

    filter = '(|' + filter + ')';
    var uuids = [];
    var req = this._morayClient.findObjects(this._VM_ROLE_TAGS_BUCKET_NAME,
        filter);

    req.once('error', function (err) {
        return cb(err);
    });

    req.on('record', function (object) {
        uuids.push(object.key);
    });

    req.once('end', function () {
        return cb(null, uuids);
    });
};


/*
 * Get all role_tags for a VM
 */
Moray.prototype.getVmRoleTags = function (uuid, cb) {
    if (!this.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    this._morayClient.getObject(this._VM_ROLE_TAGS_BUCKET_NAME, uuid,
        function (err, obj) {
        if (err) {
            if (verror.hasCauseWithName(err, 'ObjectNotFoundError')) {
                cb(null, []);
            } else {
                cb(err);
            }
        } else {
            cb(null, obj.value.role_tags);
        }
    });
};


/*
 * Puts a new role_tags object
 */
Moray.prototype.putVmRoleTags = function (uuid, roleTags, cb) {
    var object = { role_tags: roleTags };

    if (!this.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    this._morayClient.putObject(this._VM_ROLE_TAGS_BUCKET_NAME, uuid, object,
        cb);
};


/*
 * Deletes all role_tags for a VM
 */
Moray.prototype.delVmRoleTags = function (uuid, cb) {
    if (!this.bucketsSetup()) {
        cb(new Error(this._createMorayBucketsNotSetupErrMsg()));
        return;
    }

    this._morayClient.delObject(this._VM_ROLE_TAGS_BUCKET_NAME, uuid,
        function (err) {
            if (!err ||
                (err && verror.hasCauseWithName(err, 'ObjectNotFoundError'))) {
                cb(null);
            } else {
                cb(err);
            }
        });
};



/*
 * Reindexes all objects in the bucket with name "bucketName" and calls the
 * function "callback" when it's done.
 *
 * @param moray {MorayClient}
 * @param bucketName {Name of the bucket to reindex}
 * @param callback {Function} `function (err)`
 */
Moray.prototype._reindexBucket =
    function _reindexBucket(bucketName, callback) {
        assert.string(bucketName, 'bucketName');
        assert.func(callback, 'callback');

        var self = this;

        self._morayClient.reindexObjects(bucketName, 100,
            function onReindexBucketDone(reindexErr, res) {
                if (reindexErr || res.processed < 1) {
                    callback(reindexErr);
                    return;
                }

                self._reindexBucket(bucketName, callback);
            });
    };

/*
 * Reindexes all buckets represented by "bucketsConfig" and calls "callback"
 * when it's done.
 *
 * @param {Object} bucketsConfig - a map associating bucket "roles" (vms,
 *   server_vms, vms_role_tags) to objects representing their respective bucket
 *   configuration.
 *
 * @param {Function} callback - a function called when either the reindexing
 *   process is complete for all buckets, or when an error occurs. It is called
 *   as "callback(null)" if the reindexing process completed with no error, or
 *   "callback(err)"" if the error "err" occurred.
 */
Moray.prototype.reindexBuckets =
    function reindexBuckets(bucketsConfig, callback) {
    assert.object(bucketsConfig, 'bucketsConfig');
    assert.func(callback, 'callback');

    var bucketsList = [];
    var bucketConfigName;
    var self = this;

    if (self._reindexingBuckets === true) {
        throw new Error('reindexBuckets cannot be called when a reindexing ' +
            'process is in progress');
    }

    self._reindexingBuckets = true;

    for (bucketConfigName in bucketsConfig) {
        bucketsList.push(bucketsConfig[bucketConfigName]);
    }

    vasync.forEachPipeline({
        func: function reindexBucket(bucketConfig, done) {
            assert.object(bucketConfig, 'bucketConfig');
            assert.string(bucketConfig.name, 'bucketConfig.name');

            var bucketName = bucketConfig.name;

            self.log.info('Reindexing bucket ' + bucketName + '...');

            self._reindexBucket(bucketName, function reindexDone(reindexErr) {
                if (reindexErr) {
                    self.log.error({err: reindexErr},
                        'Error when reindexing bucket ' + bucketName);
                } else {
                    self.log.info('Bucket ' + bucketName +
                        ' reindexed successfully');
                }

                done(reindexErr);
            });
        },
        inputs: bucketsList
    }, function onAllBucketsReindexed(reindexErr) {
        self._reindexingBuckets = false;
        callback(reindexErr);
    });
};

module.exports = Moray;
