#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2017, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail


TOP=$(cd $(dirname $0)/../; pwd)
NODE="root@$1"

if [[ -z "$VMAPI_ZONE" ]]; then
    VMAPI_ZONE=$(ssh $NODE "vmadm lookup -1 alias=~^vmapi" 2>/dev/null)
fi
echo "VMAPI_ZONE: $VMAPI_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$VMAPI_ZONE/root/opt/smartdc/vmapi/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/zones/$VMAPI_ZONE/root/opt/smartdc/vmapi/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /boot/ \
    --exclude /config.json \
    --exclude /deps/ \
    --exclude /doc/ \
    --exclude /tools/ \
    --exclude /tmp/

rsync -av ${TOP}/boot/ \
    $NODE:/zones/$VMAPI_ZONE/root/opt/smartdc/boot/ \
    $extraOpts

state=$(ssh ${NODE} svcs -z ${VMAPI_ZONE} -H -o state vmapi)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${VMAPI_ZONE} clear vmapi
else
    ssh ${NODE} svcadm -z ${VMAPI_ZONE} restart vmapi
fi
